name: Cron Jobs on cicd-hyperv
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  run-cron:
    runs-on: cicd-hyperv
    # name: Running sample cron jobs :)
    steps:
      - name: First step of cron
        run: |
          echo "hey you this is not working anymore :()"